//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_NET_Karttapaikat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaikkaDbEntities : DbContext
    {
        public PaikkaDbEntities()
            : base("name=PaikkaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kiertue> Kiertue { get; set; }
        public virtual DbSet<KiertueEtappi> KiertueEtappi { get; set; }
        public virtual DbSet<PaikanTyyppi> PaikanTyyppi { get; set; }
        public virtual DbSet<Paikkamerkinta> Paikkamerkinta { get; set; }
        public virtual DbSet<Siirtymistapa> Siirtymistapa { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
