//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_NET_Karttapaikat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiertue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kiertue()
        {
            this.KiertueEtappi = new HashSet<KiertueEtappi>();
        }
    
        public int kiertueId { get; set; }
        public int siirtymistapaId { get; set; }
        public string kuvaus { get; set; }
    
        public virtual Siirtymistapa Siirtymistapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiertueEtappi> KiertueEtappi { get; set; }
    }
}
