//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_NET_Karttapaikat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiertueEtappi
    {
        public int etappiId { get; set; }
        public int paikkaId { get; set; }
        public int kiertueId { get; set; }
    
        public virtual Kiertue Kiertue { get; set; }
        public virtual Paikkamerkinta Paikkamerkinta { get; set; }
    }
}
