//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_NET_Karttapaikat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paikkamerkinta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paikkamerkinta()
        {
            this.KiertueEtappi = new HashSet<KiertueEtappi>();
        }
    
        public int paikkaId { get; set; }
        public double lat { get; set; }
        public double lon { get; set; }
        public int tyyppiId { get; set; }
        public string kuvaus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiertueEtappi> KiertueEtappi { get; set; }
        public virtual PaikanTyyppi PaikanTyyppi { get; set; }
    }
}
