//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_NET_Karttapaikat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaikanTyyppi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaikanTyyppi()
        {
            this.Paikkamerkinta = new HashSet<Paikkamerkinta>();
        }
    
        public int tyyppiId { get; set; }
        public string tyyppi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paikkamerkinta> Paikkamerkinta { get; set; }
    }
}
